##### title: msshin-pnc
##### email: sms0223h@hanmail.net
##### description:
##### baseurl: ""
##### url: "https://msshin-pnc.github.io/"
##### # twitter_username: msshin-pnc
##### github_username:  msshin-pnc
##### disqus_shortname: msshin-pnc
#####
##### # Build settings
##### # theme: minima
##### theme: jekyll-theme-clean-blog
##### plugins:
#####    - jekyll-feed
##### encoding: utf-8


title:              msshin-pnc
email:              sms0223h@hanmail.net
description:       Developer's Diary
author:             msshin
baseurl:            ""
url:                "https://msshin-pnc.github.io/"

# Social Profiles
# twitter_username:
github_username:    msshin-pnc
# facebook_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site